"""
Generate the Europe map geometry used by the Aftershow "Where the points landed" card
(app/src/main/java/com/example/evfunenhancer/ui/components/EuropeMapData.kt).

The app does not run this script; its output is copied into EuropeMapData.kt by hand.
Only Python 3 is needed.

INPUT
  Natural Earth 1:50m data as TopoJSON (world-atlas 2.0.2), stored next to this script in
  natural-earth/ (see the README there for source, checksums and license). No download needed.

RUN
    python3 "maintenance tools/europe_map_geo.py"
    python3 "maintenance tools/europe_map_geo.py" --detail 0.8

  --detail    coastline simplification tolerance in map units (default 1.4 ≈ 14 KB of path data).
              Smaller keeps more detail and makes the path longer.
  --data-dir  folder with land-50m.json and countries-50m.json (default: natural-earth/)
  --out       JSON output file (default: europe.json in the system temp folder, so it
              doesn't end up in the repo)

OUTPUT
  Printed:
    1. landPath check — compares the generated coastline with EuropeMap.landPath in
       EuropeMapData.kt and says "up to date", or lists the rings to remove and the rings to
       add (as Kotlin lines, ready to paste). Rings are compared as exact strings.
    2. Country centres in Kotlin form, for the `countries` table. A centre off the map is
       flagged "OUTSIDE the map frame"; one on no drawn land is flagged "on SEA".
  JSON file:
    w, h      map space size (1000 × 913.5). Must match EuropeMap.WIDTH / HEIGHT.
    land      coastline as SVG path data (all rings joined).
    centres   {country: [x, y]} in map space.
    borders   country borders; used only by design mockups, not by the app.

EuropeMap.landPath
  One Kotlin string per ring (an "M…Z" run); the app joins them and fills with the even–odd
  rule, so ring order doesn't matter and a ring inside another is a hole (the Caspian Sea).
  Some rings carry a hand-written comment (Eurasia + Africa, Caspian Sea, Iceland, Malta);
  keep those when pasting. With the bundled data and the settings below unchanged, the check
  reports "up to date"; if it doesn't, something here changed since landPath was generated.

SMALL ISLANDS
  Rings smaller than MIN_AREA (map units², after simplification) are dropped, which removes
  hundreds of islets. An exception is made for a ring that contains an entrant's centre from
  CENTRES (today only Malta): it is kept and scaled up around that centre to at least
  MIN_ISLAND units across, since at true size it would be ~2 dp on a phone. Other small
  islands near it (e.g. Gozo) are still dropped.

ADDING A COUNTRY
  1. Add it to CENTRES below as 'Name': (longitude, latitude) — use its population
     centre (usually near the capital), not its geometric middle.
  2. Run the script and copy that country's printed line into the `countries` table in
     EuropeMapData.kt. The key must be the exact English name used in participants.json;
     other spellings go in `aliases` there.
  3. Check the landPath report. Usually it says "up to date". If the new country is a small
     island (see SMALL ISLANDS), its enlarged ring is listed to add — paste it with a comment.
  4. If the centre is flagged "on SEA", move it onto land unless that is intended (Denmark's
     centre lies between its islands; that is fine, its glow covers them).

CHANGING THE FRAME OR PROJECTION (LON0/LAT0, ANCHORS, padding)
  Every coordinate moves. Replace landPath and every entry in the `countries` table, and
  update EuropeMap.HEIGHT; otherwise heat spots land in the wrong place. The Australia
  inset (EuropeMap.insetRect) is hand-placed in map space and may need moving too.
"""
import argparse, json, math, os, re, tempfile

HERE = os.path.dirname(os.path.abspath(__file__))
KOTLIN_FILE = os.path.join(HERE, '..', 'app', 'src', 'main', 'java', 'com', 'example', 'evfunenhancer',
                           'ui', 'components', 'EuropeMapData.kt')

# Lambert azimuthal equal-area, centred on Europe.
LON0, LAT0 = math.radians(15), math.radians(52)

# Frame anchors (lon, lat): Portugal/Ireland west, North Cape north, Caucasus east, Israel south.
ANCHORS = [(-10.5, 37), (-10.5, 53.5), (-9.5, 43), (26, 71.3), (31, 70.5), (45.5, 43), (46, 39), (35.5, 29.3), (34, 31)]

# Approximate population-weighted centre (lon, lat) of each current or past entrant.
# Australia is absent here: it's drawn in a hand-placed inset window (see EuropeMap.insetRect
# in EuropeMapData.kt), not generated by this script.
CENTRES = {
    'Albania': (20.0, 41.2), 'Armenia': (44.6, 40.2), 'Austria': (15.0, 47.9), 'Azerbaijan': (47.5, 40.4),
    'Belgium': (4.5, 50.8), 'Bulgaria': (25.0, 42.6), 'Croatia': (16.2, 45.3), 'Cyprus': (33.2, 35.0),
    'Czechia': (15.3, 49.9), 'Denmark': (10.5, 55.8), 'Estonia': (25.2, 58.9), 'Finland': (25.3, 61.5),
    'France': (2.4, 47.0), 'Georgia': (43.8, 42.0), 'Germany': (9.8, 51.0), 'Greece': (22.6, 39.2),
    'Iceland': (-21.5, 64.2), 'Ireland': (-7.6, 53.2), 'Israel': (34.9, 32.0), 'Italy': (12.3, 42.8),
    'Latvia': (24.5, 56.9), 'Lithuania': (24.0, 55.2), 'Luxembourg': (6.1, 49.7), 'Malta': (14.4, 35.9),
    'Moldova': (28.6, 47.1), 'Montenegro': (19.3, 42.6), 'Netherlands': (5.3, 52.2), 'North Macedonia': (21.6, 41.6),
    'Norway': (9.5, 60.5), 'Poland': (19.4, 52.0), 'Portugal': (-8.4, 39.6), 'Romania': (25.0, 45.6),
    'San Marino': (12.45, 43.94), 'Serbia': (20.7, 44.2), 'Slovenia': (14.8, 46.1), 'Spain': (-3.7, 40.2),
    'Sweden': (15.5, 59.3), 'Switzerland': (8.1, 46.9), 'Ukraine': (31.0, 49.2), 'United Kingdom': (-1.8, 52.6),
    # past / possible entrants
    'Andorra': (1.52, 42.51), 'Belarus': (27.6, 53.7), 'Bosnia and Herzegovina': (17.9, 44.1), 'Hungary': (19.5, 47.3),
    'Kosovo': (21.0, 42.6), 'Liechtenstein': (9.55, 47.15), 'Monaco': (7.42, 43.74), 'Morocco': (-6.8, 33.6),
    'Russia': (38.5, 55.3), 'Slovakia': (19.1, 48.7), 'Turkey': (31.5, 39.9),
}


def proj(lon, lat):
    l, p = math.radians(lon), math.radians(lat)
    c = 1 + math.sin(LAT0) * math.sin(p) + math.cos(LAT0) * math.cos(p) * math.cos(l - LON0)
    k = math.sqrt(2 / c)
    x = k * math.cos(p) * math.sin(l - LON0)
    y = k * (math.cos(LAT0) * math.sin(p) - math.sin(LAT0) * math.cos(p) * math.cos(l - LON0))
    return x, -y


pts = [proj(*a) for a in ANCHORS]
minx, maxx = min(p[0] for p in pts), max(p[0] for p in pts)
miny, maxy = min(p[1] for p in pts), max(p[1] for p in pts)
W = 1000.0
pad = 0.02 * (maxx - minx)
minx -= pad; maxx += pad; miny -= pad; maxy += pad
S = W / (maxx - minx)
H = (maxy - miny) * S


def to_px(lon, lat):
    x, y = proj(lon, lat)
    return (x - minx) * S, (y - miny) * S


M = 120  # points outside the frame are clamped to this margin
def clamp(p):
    return (min(max(p[0], -M), W + M), min(max(p[1], -M), H + M))


def rdp(points, eps):
    """Ramer–Douglas–Peucker line simplification."""
    if len(points) < 3:
        return points
    ax, ay = points[0]; bx, by = points[-1]
    dx, dy = bx - ax, by - ay
    L = math.hypot(dx, dy)
    dmax, idx = 0, 0
    for i in range(1, len(points) - 1):
        px, py = points[i]
        d = abs(dy * px - dx * py + bx * ay - by * ax) / L if L else math.hypot(px - ax, py - ay)
        if d > dmax:
            dmax, idx = d, i
    if dmax > eps:
        return rdp(points[:idx + 1], eps)[:-1] + rdp(points[idx:], eps)
    return [points[0], points[-1]]


def decode(topo):
    """Decode delta-encoded, quantised TopoJSON arcs into lon/lat lists."""
    sx, sy = topo['transform']['scale']; tx, ty = topo['transform']['translate']
    arcs = []
    for arc in topo['arcs']:
        x = y = 0; out = []
        for dx, dy in arc:
            x += dx; y += dy
            out.append((x * sx + tx, y * sy + ty))
        arcs.append(out)
    return arcs


def ring_coords(ring, arcs):
    out = []
    for i in ring:
        a = arcs[i] if i >= 0 else arcs[~i][::-1]
        out.extend(a if not out else a[1:])
    return out


def in_region(lon, lat):
    return -32 < lon < 60 and 25 < lat < 75


def visible(poly):
    return any(-5 < x < W + 5 and -5 < y < H + 5 for x, y in poly)


def contains(poly, pt):
    """Even–odd point-in-polygon test."""
    x, y = pt
    inside = False
    for (x1, y1), (x2, y2) in zip(poly, poly[1:] + poly[:1]):
        if (y1 > y) != (y2 > y) and x < x1 + (y - y1) * (x2 - x1) / (y2 - y1):
            inside = not inside
    return inside


def ring_area(poly):
    return 0.5 * abs(sum(poly[i][0] * poly[i - 1][1] - poly[i - 1][0] * poly[i][1] for i in range(len(poly))))


# Rings smaller than this (map units²) are dropped, unless an entrant's centre lies on them.
MIN_AREA = 40
# An entrant's own island is scaled up around its centre until it is at least this wide or
# tall (map units), so it stays visible on a phone (Malta is ~7 units long at true scale).
MIN_ISLAND = 14


def exaggerate(poly, centre):
    xs = [p[0] for p in poly]; ys = [p[1] for p in poly]
    k = MIN_ISLAND / max(max(xs) - min(xs), max(ys) - min(ys))
    if k <= 1:
        return poly
    cx, cy = centre
    return [(cx + (x - cx) * k, cy + (y - cy) * k) for x, y in poly]


def fmt(poly, close):
    s = 'M' + ' '.join(f'{x:.0f},{y:.0f}' for x, y in poly)
    return s + ('Z' if close else '')


def report_land_changes(paths):
    """Compare generated rings with EuropeMap.landPath and print what to change there."""
    try:
        kt = open(KOTLIN_FILE, encoding='utf-8').read()
        block = kt[kt.index('val landPath'):kt.index('.joinToString', kt.index('val landPath'))]
    except (OSError, ValueError):
        print(f'\nlandPath check skipped: could not read landPath from {KOTLIN_FILE}')
        return
    current = re.findall(r'"(M[^"]*)"', block)
    removed = [r for r in current if r not in paths]
    added = [r for r in paths if r not in current]
    if not removed and not added:
        print('\nlandPath in EuropeMapData.kt is up to date.')
        return
    print(f'\nlandPath in EuropeMapData.kt differs: {len(removed)} ring(s) to remove, {len(added)} to add.')
    for r in removed:
        print(f'  remove: "{r[:60]}…"')
    if added:
        print('  add (Kotlin, one per ring):')
        for r in added:
            print(f'        "{r}",')


def main():
    ap = argparse.ArgumentParser(description='Generate Europe map geometry for EuropeMapData.kt.')
    ap.add_argument('--data-dir', default=os.path.join(HERE, 'natural-earth'),
                    help='folder containing land-50m.json and countries-50m.json (default: natural-earth/)')
    ap.add_argument('--detail', type=float, default=1.4, help='coastline simplification tolerance (default 1.4)')
    ap.add_argument('--out', default=os.path.join(tempfile.gettempdir(), 'europe.json'),
                    help='JSON output file (default: europe.json in the system temp folder)')
    args = ap.parse_args()
    eps = args.detail

    cpx = {k: [round(v, 1) for v in to_px(*ll)] for k, ll in CENTRES.items()}

    land = json.load(open(os.path.join(args.data_dir, 'land-50m.json')))
    larcs = decode(land)
    paths = []
    kept = []  # final rings, for the centre-on-land check below
    for geom in land['objects']['land']['geometries']:
        polys = geom['arcs'] if geom['type'] == 'MultiPolygon' else [geom['arcs']]
        for poly in polys:
            for ring in poly:
                ll = ring_coords(ring, larcs)
                if not any(in_region(*p) for p in ll):
                    continue
                px = [clamp(to_px(*p)) for p in ll if -60 < p[0] < 120]
                if len(px) < 3 or not visible(px):
                    continue
                # A small island that is itself an entrant (Malta) is kept and exaggerated.
                owner = next((c for c in cpx.values() if contains(px, c)), None)
                if owner and ring_area(px) < MIN_AREA:
                    px = rdp(exaggerate(px, owner), min(eps, 0.8))
                    paths.append(fmt(px, True)); kept.append(px)
                    continue
                px = rdp(px, eps)
                if len(px) < 4:
                    continue
                # drop tiny islands
                if ring_area(px) < MIN_AREA:
                    continue
                paths.append(fmt(px, True)); kept.append(px)
    land_d = ''.join(paths)

    # Borders = arcs shared by two or more countries.
    countries = json.load(open(os.path.join(args.data_dir, 'countries-50m.json')))
    carcs = decode(countries)
    ref = {}
    for geom in countries['objects']['countries']['geometries']:
        polys = geom['arcs'] if geom['type'] == 'MultiPolygon' else [geom['arcs']]
        for poly in polys:
            for ring in poly:
                for i in ring:
                    k = i if i >= 0 else ~i
                    ref[k] = ref.get(k, 0) + 1
    bpaths = []
    for k, n in ref.items():
        if n < 2:
            continue
        ll = carcs[k]
        if not any(in_region(*p) for p in ll):
            continue
        px = [clamp(to_px(*p)) for p in ll]
        if not visible(px):
            continue
        bpaths.append(fmt(rdp(px, eps), False))
    border_d = ''.join(bpaths)

    json.dump({'w': W, 'h': round(H, 1), 'land': land_d, 'borders': border_d, 'centres': cpx}, open(args.out, 'w'))
    print(f'Wrote {args.out}: map {W:.0f} × {H:.1f}, land {len(land_d)} B in {len(paths)} rings, borders {len(border_d)} B')
    report_land_changes(paths)
    print('\nCountry centres (Kotlin, for the `countries` table):')
    for name, (x, y) in sorted(cpx.items()):
        inside = 0 <= x <= W and 0 <= y <= H
        # Even–odd across all rings, matching the app's fill (the Caspian is a hole).
        on_land = sum(contains(r, (x, y)) for r in kept) % 2 == 1
        note = '' if inside and on_land else '   // OUTSIDE the map frame' if not inside else '   // on SEA: no land drawn here'
        print(f'    {json.dumps(name, ensure_ascii=False)} to Offset({x}f, {y}f),{note}')


if __name__ == '__main__':
    main()
